# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 669ef284a6ac9f1f8cfae773fdabd8ac49f279838696d017386d11e1c7527663a090a7b3108e0e7f47c025299c35ae7d9f0ac94841fccf92d923dedcd6d21dc3
  rest_sync_realtime: true
  rest_sync_root: "http://127.0.0.1:3010"

test:
  secret_key_base: 17f4fba08f2914cde07e54016064829ce570590339ddb725b200ac8492dea31cc82284c8068f5fca3ba08eb873976ffcbcb8998ca931c8db3af1da079ba4f262


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rest_sync_realtime: true
  rest_sync_root: "http://"
